In [2]:
# 1. Tạo numpy array arr có giá trị từ 0-9. Hiển thị các phần tử có trong arr, xem kiểu dữ liệu và kích thước của arr.

import numpy as np 

array_arr = np.array([0,1,2,3,4,5,6,7,8,9]) # cũng có thể dungf hàm np.arange(10)

print('Hiển thị các phần tử có trong arr là :')
print(array_arr)
print('Kiểu dữ liệu là :',array_arr.dtype)
print('Kích thước của các phần tử là :',array_arr.shape)

Hiển thị các phần tử có trong arr là :
[0 1 2 3 4 5 6 7 8 9]
Kiểu dữ liệu là : int32
Kích thước của các phần tử là : (10,)


In [3]:
# 2.Từ array arr ở câu 1 => tạo arr_odd và arr_even.
# Phần tử lẻ :
arr_odd = array_arr[array_arr % 2 != 0]
print('Mảng của phần tử lẻ là :')
print(arr_odd)

# Phần tử chẵn :
arr_even = array_arr[array_arr % 2 == 0]
print("Mảng của phần tử chẵn là :")
print(arr_even)

Mảng của phần tử lẻ là :
[1 3 5 7 9]
Mảng của phần tử chẵn là :
[0 2 4 6 8]


In [4]:
# 3.Từ array arr ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100.

arr_update_1 = np.where(array_arr % 2 == 0 , array_arr , 100 )

print(arr_update_1)
 

[  0 100   2 100   4 100   6 100   8 100]
