In [19]:
import numpy as np


In [20]:
# 1. Tạo array arr có kích thước 3x3 với các giá trị True
arr = np.full((3, 3), True)
print("Array arr:")
print(arr)

Array arr:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [21]:
# 2. Tạo array 2 chiều từ arr_1D và chuyển cột 1 sang cột 3 và ngược lại
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape((3, 3))
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("\nArray arr_2D:")
print(arr_2D)


Array arr_2D:
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [22]:
# 3. Chuyển dòng 1 sang dòng 2 và ngược lại
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("\n3. Array arr_2D after swapping rows:")
print(arr_2D)


3. Array arr_2D after swapping rows:
[[5 4 3]
 [2 1 0]
 [8 7 6]]


In [23]:
# 4. Đảo ngược các dòng của arr_2D
arr_2D = arr_2D[::-1, :]
print("\nĐảo ngược các dòng của arr_2D:")
print(arr_2D)


Đảo ngược các dòng của arr_2D:
[[8 7 6]
 [2 1 0]
 [5 4 3]]


In [24]:
# 5. Đảo ngược các cột của arr_2D
arr_2D = arr_2D[:, ::-1]
print("\nĐảo ngược các cột của arr_2D:")
print(arr_2D)


Đảo ngược các cột của arr_2D:
[[6 7 8]
 [0 1 2]
 [3 4 5]]


In [25]:
# 6. Kiểm tra trong array có giá trị rỗng không
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
has_nan = np.isnan(arr_2D_null).any()
print("\nKiểm tra trong array có giá trị rỗng không :", has_nan)


Kiểm tra trong array có giá trị rỗng không : True


In [26]:
# 7. Thay thế giá trị null bằng 0
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\nThay thế giá trị null bằng 0:")
print(arr_2D_null)


Thay thế giá trị null bằng 0:
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
