In [5]:
import numpy as np 

#1. Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1.

# Tạo mảng có 10 phần tử là 0 : 

arr_zeros = np.zeros(10)

print('mảng có 10 phần tử là 0 :')
print(arr_zeros)

# Cập nhật phần tử ở vị trí thứ 5 là 1.

arr_zeros[4] = 1

print('Cập nhập phần tử ở vị trí thứ 5 là 1 : ')

print(arr_zeros)






mảng có 10 phần tử là 0 :
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Cập nhập phần tử ở vị trí thứ 5 là 1 : 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
#2. Tạo arr_h có giá trị từ 10 đến 24. In danh sách các phần tử theo tứ tự đảo ngược của arr_h.

# Tạo arr_h có giá trị từ 10 đến 24 :

arr_h = np.arange(10,25)

print('Mảng arr_h từ 10 đến 24 là : ')
print(arr_h)

# In danh sách các phần tử theo tứ tự đảo ngược của arr_h.

print('Danh sách các phần tử theo thứ tự đảo ngược của arr_h là :',arr_h[::-1])

Mảng arr_h từ 10 đến 24 là : 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Danh sách các phần tử theo thứ tự đảo ngược của arr_h là : [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [23]:
#3. Cho arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]), tạo arr_l từ arr_k với các phần tử khác 0.

arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])

arr_l = arr_k[arr_k != 0 ]

print(arr_l)

[1 2 8 2 1 3 5]


In [24]:
#3. Từ arr_l của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array.

arr_l = np.append(arr_l,[10,20])
print('Mảng sau khi được thêm là :')
print(arr_l)

Mảng sau khi được thêm là :
[ 1  2  8  2  1  3  5 10 20]


In [33]:
#5.Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5 

arr_l = np.array([1,2,8,2,1 ,3,5,10,20])

arr_l = np.insert(arr_l, 5,100)
print('Mảng sau khi được thêm là : ')
print(arr_l)

Mảng sau khi được thêm là : 
[  1   2   8   2   1 100   3   5  10  20]


In [40]:
#6 .Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2.

arr_l = np.array([ 1,2,8,2,1,100,3,5,10,20])

arr_l = np.delete(arr_l,[0,1,2])

print('Mảng sau khi được thêm là : ')
print(arr_l)

Mảng sau khi được thêm là : 
[  2   1 100   3   5  10  20]
